### ISSUE TITLE
ImportError trying to use session management

### ISSUE THREAD

**Issue by maxicecilia** [juanifioren/django-oidc-provider#148]
I'm trying to use the session management feature as described in the [docs](http://django-oidc-provider.readthedocs.io/en/stable/sections/sessionmanagement.html), but I'm getting this error:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/home/mcecilia/.virtualenvs/mmdb_reload/local/lib/python2.7/site-packages/django/contrib/staticfiles/handlers.py", line 63, in __call__
    return self.application(environ, start_response)
  File "/home/mcecilia/.virtualenvs/mmdb_reload/src/universe-utils/universe_utils/middleware/reverse_proxy.py", line 34, in __call__
    return self.app(environ, start_response)
  File "/home/mcecilia/.virtualenvs/mmdb_reload/local/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 170, in __call__
    self.load_middleware()
  File "/home/mcecilia/.virtualenvs/mmdb_reload/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 50, in load_middleware
    mw_class = import_string(middleware_path)
  File "/home/mcecilia/.virtualenvs/mmdb_reload/local/lib/python2.7/site-packages/django/utils/module_loading.py", line 26, in import_string
    module = import_module(module_path)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/mcecilia/.virtualenvs/mmdb_reload/local/lib/python2.7/site-packages/oidc_provider/middleware.py", line 4, in <module>
    from django.utils.deprecation import MiddlewareMixin
ImportError: cannot import name MiddlewareMixin
```

I'm using 
```
django-oidc-provider==0.4.4
Django==1.8.15
```
and the MiddlewareMixin exists only in Django 1.10.x

**Comment by juanifioren** [comment]
Yes. I we need compatibility for older Django versions.
