### ISSUE TITLE
 File "/usr/local/lib/python3.5/dist-packages/django/contrib/sessions/backends/base.py", line 57, in __getitem__     return self._session[key] KeyError: 'op'

### ISSUE THREAD

**Issue by Allan-Nava** [juanifioren/django-oidc-provider#234]
Hi, i have this error:

```
Internal Server Error: /openid/callback/login/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/djangooidc/views.py", line 86, in authz_cb
    client = CLIENTS[request.session["op"]]
  File "/usr/local/lib/python3.5/dist-packages/django/contrib/sessions/backends/base.py", line 57, in __getitem__
    return self._session[key]
KeyError: 'op'

```

**Comment by juanifioren** [comment]
This error belongs to another implementation of an OIDC Client.
https://github.com/marcanpilami/django-oidc/blob/master/djangooidc/views.py#L81

Only reading code, maybe you need to complete some kind of form providing server provider information.
https://github.com/marcanpilami/django-oidc/blob/master/djangooidc/views.py#L48

**Comment by Allan-Nava** [comment]
Yes, but it seems that in ` oidc(request) ` function, request.session is with needed information, but in `authn_cb(request, op_name=None)` it crashes, because session has no both 'op' and 'next' parameters.

How can we do?
