### ISSUE TITLE
An example project does not support Django 2.1

### ISSUE THREAD

**Issue by yuta1024** [juanifioren/django-oidc-provider#302]
An example project does not work when use Django 2.1.
```
$ python --version
Python 3.6.7
$ pip list | grep Django
Django               2.1.4
$ python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/yuta1024/.pyenv/versions/oidc/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/Users/yuta1024/.pyenv/versions/oidc/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/yuta1024/.pyenv/versions/oidc/lib/python3.6/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/yuta1024/.pyenv/versions/oidc/lib/python3.6/site-packages/django/core/management/base.py", line 350, in execute
    self.check()
  File "/Users/yuta1024/.pyenv/versions/oidc/lib/python3.6/site-packages/django/core/management/base.py", line 379, in check
    include_deployment_checks=include_deployment_checks,
  File "/Users/yuta1024/.pyenv/versions/oidc/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 60, in _run_checks
    issues.extend(super()._run_checks(**kwargs))
  File "/Users/yuta1024/.pyenv/versions/oidc/lib/python3.6/site-packages/django/core/management/base.py", line 366, in _run_checks
    return checks.run_checks(**kwargs)
  File "/Users/yuta1024/.pyenv/versions/oidc/lib/python3.6/site-packages/django/core/checks/registry.py", line 71, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/Users/yuta1024/.pyenv/versions/oidc/lib/python3.6/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/Users/yuta1024/.pyenv/versions/oidc/lib/python3.6/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/Users/yuta1024/.pyenv/versions/oidc/lib/python3.6/site-packages/django/urls/resolvers.py", line 396, in check
    for pattern in self.url_patterns:
  File "/Users/yuta1024/.pyenv/versions/oidc/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/yuta1024/.pyenv/versions/oidc/lib/python3.6/site-packages/django/urls/resolvers.py", line 533, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/yuta1024/.pyenv/versions/oidc/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/yuta1024/.pyenv/versions/oidc/lib/python3.6/site-packages/django/urls/resolvers.py", line 526, in urlconf_module
    return import_module(self.urlconf_name)
  File "/Users/yuta1024/.pyenv/versions/3.6.7/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/yuta1024/Workspace/oidc/django-oidc-provider/example/app/urls.py", line 12, in <module>
    url(r'^accounts/login/$', auth_views.login, {'template_name': 'login.html'}, name='login'),
AttributeError: module 'django.contrib.auth.views' has no attribute 'login'
```

In Django 2.1, `contrib.auth.views.login(), logout()` was removed.
https://docs.djangoproject.com/en/2.1/releases/2.1/#features-removed-in-2-1

Applying the following patch, it worked fine.
```
$ git diff
diff --git a/example/app/urls.py b/example/app/urls.py
index 2b0a624..c975574 100644
--- a/example/app/urls.py
+++ b/example/app/urls.py
@@ -9,8 +9,8 @@ from django.views.generic import TemplateView

 urlpatterns = [
     url(r'^$', TemplateView.as_view(template_name='home.html'), name='home'),
-    url(r'^accounts/login/$', auth_views.login, {'template_name': 'login.html'}, name='login'),
-    url(r'^accounts/logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),
+    url(r'^accounts/login/$', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
+    url(r'^accounts/logout/$', auth_views.LogoutView.as_view(next_page='/'), name='logout'),
     url(r'^', include('oidc_provider.urls', namespace='oidc_provider')),
     url(r'^admin/', admin.site.urls),
 ]
```

If there is no problem with this patch I will send PR.
Thanks.

**Comment by juanifioren** [comment]
Hi @yuta1024, sure send PR please

**Comment by yuta1024** [comment]
@juanifioren Thanks. I sent PR(#303).
