### ISSUE TITLE
Another installation error

### ISSUE THREAD

**Issue by shepelevstas** [juanifioren/django-oidc-provider#330]
Hello! Trying to follow Installation instructions from the docs I get an error right after this command:
`$ python manage.py migrate`
the error:
```
(venv) C:\Users\we\Projects\web\hex\s>manage.py migrate
Traceback (most recent call last):
  File "C:\Users\we\Projects\web\hex\s\manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\we\Projects\web\hex\venv\lib\site-packages\django\core\management\__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "C:\Users\we\Projects\web\hex\venv\lib\site-packages\django\core\management\__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\we\Projects\web\hex\venv\lib\site-packages\django\core\management\base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\we\Projects\web\hex\venv\lib\site-packages\django\core\management\base.py", line 342, in execute
    self.check()
  File "C:\Users\we\Projects\web\hex\venv\lib\site-packages\django\core\management\base.py", line 374, in check
    include_deployment_checks=include_deployment_checks,
  File "C:\Users\we\Projects\web\hex\venv\lib\site-packages\django\core\management\commands\migrate.py", line 62, in _run_checks
    issues.extend(super(Command, self)._run_checks(**kwargs))
  File "C:\Users\we\Projects\web\hex\venv\lib\site-packages\django\core\management\base.py", line 361, in _run_checks
    return checks.run_checks(**kwargs)
  File "C:\Users\we\Projects\web\hex\venv\lib\site-packages\django\core\checks\registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "C:\Users\we\Projects\web\hex\venv\lib\site-packages\django\core\checks\urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "C:\Users\we\Projects\web\hex\venv\lib\site-packages\django\core\checks\urls.py", line 24, in check_resolver
    for pattern in resolver.url_patterns:
  File "C:\Users\we\Projects\web\hex\venv\lib\site-packages\django\utils\functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\we\Projects\web\hex\venv\lib\site-packages\django\urls\resolvers.py", line 313, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\Users\we\Projects\web\hex\venv\lib\site-packages\django\utils\functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\we\Projects\web\hex\venv\lib\site-packages\django\urls\resolvers.py", line 306, in urlconf_module
    return import_module(self.urlconf_name)
  File "C:\Program Files (x86)\Python36-32\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\we\Projects\web\hex\s\s\urls.py", line 21, in <module>
    url(r'^openid/', include('oidc_provider.urls', namespace='oidc_provider')),
  File "C:\Users\we\Projects\web\hex\venv\lib\site-packages\django\conf\urls\__init__.py",
line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "C:\Program Files (x86)\Python36-32\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\we\Projects\web\hex\venv\lib\site-packages\oidc_provider\urls.py", line 7, in <module>
    from oidc_provider import (
  File "C:\Users\we\Projects\web\hex\venv\lib\site-packages\oidc_provider\views.py", line 13, in <module>
    from django.contrib.auth.views import (
ImportError: cannot import name 'LogoutView'
```

Don't know what is means, except there is no `LogoutView` in `django.contrib.auth.views`.
I use Django 1.10
On Windows 8.1 64bit

**Comment by juanifioren** [comment]
Hi @shepelevstas which version of `django-oidc-provider` ?? last version we drop support for `django` lower than `1.11`
https://django-oidc-provider.readthedocs.io/en/latest/sections/changelog.html#id2

**Comment by shepelevstas** [comment]
I see. Thank you. The Installation docs still state the support for versions of Django 1.8+

**Comment by juanifioren** [comment]
True. Changing... thanks for reporting :+1:
