### ISSUE TITLE
not working with djongo/mongodb

### ISSUE THREAD

**Issue by jesusch** [juanifioren/django-oidc-provider#331]
while using djongo as a database backend (https://nesdis.github.io/djongo/), django-oidc-provider cannot run its migrations fully

trace:

Running migrations:
  Applying oidc_provider.0001_initial... OK
  Applying oidc_provider.0002_userconsent... OK
  Applying oidc_provider.0003_code_nonce... OK
  Applying oidc_provider.0004_remove_userinfo... OK
  Applying oidc_provider.0005_token_refresh_token...Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/djongo/sql2mongo/query.py", line 819, in parse
    return handler(self, statement)
  File "/usr/local/lib/python3.7/site-packages/djongo/sql2mongo/query.py", line 849, in _alter
    self._query.execute()
  File "/usr/local/lib/python3.7/site-packages/djongo/sql2mongo/query.py", line 697, in _unique
    self.field_dir,
AttributeError: 'AlterQuery' object has no attribute 'field_dir'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/commands/migrate.py", line 234, in handle
    fake_initial=fake_initial,
  File "/usr/local/lib/python3.7/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.7/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.7/site-packages/django/db/migrations/executor.py", line 245, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python3.7/site-packages/django/db/migrations/migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/local/lib/python3.7/site-packages/django/db/migrations/operations/fields.py", line 112, in database_forwards
    field,
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/schema.py", line 447, in add_field
    self.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/schema.py", line 137, in execute
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/djongo/cursor.py", line 53, in execute
    params)
  File "/usr/local/lib/python3.7/site-packages/djongo/sql2mongo/query.py", line 754, in __init__
    self.parse()
  File "/usr/local/lib/python3.7/site-packages/djongo/sql2mongo/query.py", line 841, in parse
    raise exe from e
djongo.sql2mongo.SQLDecodeError: FAILED SQL: ALTER TABLE "oidc_provider_token" ADD COLUMN "refresh_token" string NULL UNIQUE
Params: []
Version: 1.2.33

**Comment by juanifioren** [comment]
Hi @jesusch don't know what to tell you! since we are using only the official django databases. Please provide python, packages & mongo versions.
