### ISSUE TITLE
get_issuer returns a wrong value

### ISSUE THREAD

**Issue by pabluk** [juanifioren/django-oidc-provider#72]
I think that the issuer value sent by `/.well-known/openid-configuration/` is wrong:
```
$ curl "https://id.seminar.io/openid/.well-known/openid-configuration/" | python -m json.tool
{
    "authorization_endpoint": "https://id.seminar.io/openid/authorize",
    "end_session_endpoint": "https://id.seminar.io/openid/logout",
    "id_token_signing_alg_values_supported": [
        "RS256"
    ],
    "issuer": "https://id.seminar.io/openid/.well-known/openid-configuration",
    "jwks_uri": "https://id.seminar.io/openid/jwks",
    "response_types_supported": [
        "code",
        "id_token",
        "id_token token"
    ],
    "subject_types_supported": [
        "public"
    ],
    "token_endpoint": "https://id.seminar.io/openid/token",
    "token_endpoint_auth_methods_supported": [
        "client_secret_post",
        "client_secret_basic"
    ],
    "userinfo_endpoint": "https://id.seminar.io/openid/userinfo"
}
```
using the oic library I see this error:
```
>>> client.provider_config("https://id.seminar.io/openid/")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pabluk/temp/venv/local/lib/python2.7/site-packages/oic/oic/__init__.py", line 917, in provider_config
    self.handle_provider_config(pcr, issuer, keys, endpoints)
  File "/home/pabluk/temp/venv/local/lib/python2.7/site-packages/oic/oic/__init__.py", line 868, in handle_provider_config
    pcr)
oic.exception.IssuerMismatch: 'https://id.seminar.io/openid' != 'http://id.seminar.io/openid/.well-known/openid-configuration'
>>> 
```
and looking at https://github.com/juanifioren/django-oidc-provider/blob/v0.2.3/oidc_provider/lib/utils/common.py#L23:L24 I see that the value returned by `reverse('oidc_provider:provider_info')` has no ending slash:
```
>>> from django.core.urlresolvers import reverse
>>> reverse('oidc_provider:provider_info')
u'/openid/.well-known/openid-configuration'
>>> reverse('oidc_provider:provider_info').split('/.well-known/openid-configuration/')
[u'/openid/.well-known/openid-configuration']
```
so it's never split.

**Comment by juanifioren** [comment]
Cool @pabluk! 
Never realize that :+1:
